services:
  app1:
    image: tomcat
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "grep", ":1F90", "/proc/net/tcp"]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - bridge

  app2:
    image: tomcat
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "grep", ":1F90", "/proc/net/tcp"]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - bridge

  app3:
    image: tomcat
    ports:
      - "8083:8080"
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
